Update Infra.yml

diff --git a/.github/workflows/Infra.yml b/.github/workflows/Infra.yml
--- a/.github/workflows/Infra.yml
+++ b/.github/workflows/Infra.yml
@@ -34,16 +34,24 @@ jobs:
         with:
           terraform_version: 1.5.5
 
-      # # Step: Set up TFLint
-      # # Step: Install TFLint
-      # - name: Install TFLint
-      #   run: |
-      #    curl -LO https://github.com/terraform-linters/tflint/releases/download/v0.55.0/tflint-linux-amd64.zip
+      - name: Install TFLint
+        run: |
+          TFLINT_VERSION="v0.55.0"
+          curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
+          
+          if [ ! -s "tflint.zip" ]; then
+            echo "Error: Downloaded TFLint archive is empty or invalid."
+            exit 1
+          fi
 
-      #    unzip tflint-linux-amd64.zip
-      #    sudo mv tflint /usr/local/bin/
-      #    rm tflint-linux-amd64.zip
-      #    tflint --version
+          unzip tflint.zip
+          chmod +x tflint
+          sudo mv tflint /usr/local/bin/
+          rm tflint.zip
+          
+          echo "TFLint installed successfully:"
+          tflint --version
+
 
 
       # # Step: Run TFLint to check for issues in the Terraform code
